name: API Requester
on:
  push:
    branches:
      - 'main'
    paths:
      - 'aprsfiBasic.py'
  workflow_dispatch:

jobs:
  Setup:
    name: Setup Ubuntu runner
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@main
    - name: Test API
      run: |
        python aprsfiBasic.py
